# Generated by Django 2.0.6 on 2019-01-21 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder_number', models.CharField(max_length=200)),
                ('machine_size', models.IntegerField(default=0)),
                ('machine_type', models.CharField(max_length=200)),
                ('due_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
