# Generated by Django 2.0.6 on 2019-02-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_urgent_within', models.IntegerField(default=15)),
                ('refresh_rate_seconds', models.IntegerField(default=7)),
                ('rows_per_page', models.IntegerField(default=4)),
                ('debug', models.BooleanField(default=False)),
            ],
        ),
    ]
